{
 "title": "Postgres",
 "tags": [ "cloudnativepg" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "operatorNamespace",
    "label": "Operator Namespace",
    "query": {
     "query": "label_values(controller_runtime_webhook_requests_total{webhook=\"/mutate-postgresql-cnpg-io-v1-cluster\"},namespace)"
    }
   },
   { "name": "namespace", "label": "Database Namespace", "query": "${VAR_NAMESPACE}" },
   {
    "name": "cluster",
    "label": "DB Cluster",
    "query": {
     "query": "cnpg_collector_up{namespace=~\"$namespace\"}"
    }
   },
   {
    "name": "instances",
    "label": "Instances",
    "query": {
     "query": "cnpg_collector_up{namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"}"
    }
   },
   { "name": "k8s_cluster", "label": "Kubernetes Cluster", "query": "${VAR_K8S_CLUSTER}" }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 } },
  { "title": "Health", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 3, "y": 0 } },
  { "title": "Overview", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 7, "y": 0 } },
  { "title": "Storage", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 19, "y": 0 } },
  { "title": "Backups", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 21, "y": 0 } },
  {
   "type": "stat",
   "description": "Cluster Replication Health represents the availability of replica servers available to replace the primary in case of a failure.",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "(max(cnpg_pg_replication_streaming_replicas{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\", pod=~\"$instances\"}) - sum(cnpg_pg_replication_is_wal_receiver_up{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\", pod=~\"$instances\"})) + (clamp_max(max(cnpg_pg_replication_streaming_replicas{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\", pod=~\"$instances\"}), 1) - 1)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "High lag indicates issue with replication. Network or storage interfaces may not have enough bandwidth to handle incoming traffic and replication at the same time.",
   "gridPos": { "h": 2, "w": 1, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "max(cnpg_pg_replication_lag{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}) + max(cnpg_pg_stat_replication_write_lag_seconds{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}) + max(cnpg_pg_stat_replication_flush_lag_seconds{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}) + max(cnpg_pg_stat_replication_replay_lag_seconds{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"})"
    },
    { "app": "grafana-assistant-app" }
   ]
  },
  {
   "type": "stat",
   "description": "Low disk space or low inode count will result in data loss.",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "max((max(max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"}))) OR (max by(persistentvolumeclaim) (kubelet_volume_stats_inodes_used{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"} / kubelet_volume_stats_inodes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"})))"
    }
   ]
  },
  {
   "title": "Last failover",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "max(cnpg_pg_postmaster_start_time{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"})*1000"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "sum(rate(cnpg_pg_stat_database_xact_commit{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}[$__interval])) + sum(rate(cnpg_pg_stat_database_xact_rollback{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "gauge",
   "description": "CPU Utilisation from Requests",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", pod=~\"$instances\"}) / sum(kube_pod_container_resource_requests{cluster=~\"$k8s_cluster\",job=\"kube-state-metrics\",  namespace=\"$namespace\", resource=\"cpu\", pod=~\"$instances\"})"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "gauge",
   "description": "Memory Utilisation from Requests",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"$k8s_cluster\",job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container!=\"\", image!=\"\", pod=~\"$instances\"}) / sum(max by(pod) (kube_pod_container_resource_requests{cluster=~\"$k8s_cluster\",job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\", pod=~\"$instances\"}))"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "max(cnpg_pg_replication_lag{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"})"
    }
   ]
  },
  {
   "title": "Write Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "max(cnpg_pg_stat_replication_write_lag_seconds{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"})"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "max(max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"}))",
     "legendFormat": "PGDATA"
    },
    {
     "app": "grafana-assistant-app",
     "expr": "max(max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"}))",
     "legendFormat": "WAL"
    },
    {
     "app": "grafana-assistant-app",
     "expr": "max(\n    sum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-tbs.*\"}) \n    /\n    sum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-tbs.*\"}) \n    *\n    on(namespace, persistentvolumeclaim) group_left(volume)\n    kube_pod_spec_volumes_persistentvolumeclaims_info{cluster=~\"$k8s_cluster\",pod=~\"$instances\"}\n)",
     "legendFormat": "Tablespace"
    }
   ]
  },
  {
   "title": "Last Base Backup",
   "type": "stat",
   "description": "Elapsed time since the last successful base backup.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "-(time() - max({__name__=~\"cnpg_collector_last_available_backup_timestamp|barman_cloud_cloudnative_pg_io_last_available_backup_timestamp\",cluster=~\"$k8s_cluster\",namespace=\"$namespace\",pod=~\"$instances\"}))"
    }
   ]
  },
  {
   "type": "stat",
   "description": "High resource usage (CPU, Memory, DB Connections)",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$k8s_cluster\", namespace=\"$namespace\", pod=~\"$instances\"}) / sum(kube_pod_container_resource_requests{cluster=~\"$k8s_cluster\",job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\", pod=~\"$instances\"}))"
    },
    {
     "app": "grafana-assistant-app",
     "expr": "(sum(container_memory_working_set_bytes{cluster=~\"$k8s_cluster\",job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container!=\"\", image!=\"\", pod=~\"$instances\"}) / sum(max by(pod) (kube_pod_container_resource_requests{cluster=~\"$k8s_cluster\",job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\", pod=~\"$instances\"})))"
    },
    {
     "app": "grafana-assistant-app",
     "expr": " (max(sum by (pod) (cnpg_backends_total{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\", pod=~\"$instances\"}) / sum by (pod) (cnpg_pg_settings_setting{cluster=~\"$k8s_cluster\",name=\"max_connections\", namespace=~\"$namespace\", pod=~\"$instances\"})))"
    }
   ]
  },
  {
   "title": "Last archived WAL",
   "type": "stat",
   "description": "Computes the time since the last known WAL archival in the primary.\nWe ensure to ignore the metric in the replicas by using (1 - cnpg_pg_replication_in_recovery ) as a multiplicative factor. It will be 0 for replicas, 1 for the primary.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "max((1 - cnpg_pg_replication_in_recovery{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}) * (time() - timestamp(cnpg_pg_stat_archiver_seconds_since_last_archival{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}) +\ncnpg_pg_stat_archiver_seconds_since_last_archival{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}))"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "cnpg_collector_postgres_version{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Flush Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "max(cnpg_pg_stat_replication_flush_lag_seconds{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"})"
    }
   ]
  },
  {
   "title": "Replay Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "max(cnpg_pg_stat_replication_replay_lag_seconds{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Base Backups are considered healthy when there has been at least one base backup in the last 24 hours.",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "time() - max({__name__=~\"cnpg_collector_last_available_backup_timestamp|barman_cloud_cloudnative_pg_io_last_available_backup_timestamp\",cluster=~\"$k8s_cluster\",namespace=\"$namespace\", pod=~\"$instances\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "WAL is considered Healthy when the last WAL is 0min to 6min old, Delayed when it is less than 15min and Unsynced for >15min.",
   "gridPos": { "h": 2, "w": 1, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "max((1 - cnpg_pg_replication_in_recovery{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\", pod=~\"$instances\"}) * (time() - timestamp(cnpg_pg_stat_archiver_seconds_since_last_archival{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\", pod=~\"$instances\"}) +\ncnpg_pg_stat_archiver_seconds_since_last_archival{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\", pod=~\"$instances\"}))"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Online if there is at least one ready operator pod",
   "gridPos": { "h": 2, "w": 1, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "sum(kube_pod_status_ready{cluster=~\"$k8s_cluster\",namespace=\"$operatorNamespace\", pod=~\"cloudnative-pg.+|cnpg-controller-manager.+\", condition=\"true\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "clamp_max(max(controller_runtime_reconcile_total{cluster=~\"$k8s_cluster\",namespace=~\"$operatorNamespace\", result=\"error\", controller=\"backup\"}), 1)"
    },
    {
     "app": "grafana-assistant-app",
     "expr": "clamp_max(max(controller_runtime_reconcile_total{cluster=~\"$k8s_cluster\",namespace=~\"$operatorNamespace\", result=\"error\", controller=\"cluster\"}), 1)"
    },
    {
     "app": "grafana-assistant-app",
     "expr": "clamp_max(max(controller_runtime_reconcile_total{cluster=~\"$k8s_cluster\",namespace=~\"$operatorNamespace\", result=\"error\", controller=\"pooler\"}), 1)"
    },
    {
     "app": "grafana-assistant-app",
     "expr": "clamp_max(max(controller_runtime_reconcile_total{cluster=~\"$k8s_cluster\",namespace=~\"$operatorNamespace\", result=\"error\", controller=~\"scheduledbackup|scheduled-backup\"}), 1)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", pod=~\"$instances\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Container memory working set",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"$k8s_cluster\",pod=~\"$instances\", namespace=\"$namespace\", container!=\"\", image!=\"\"})"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "cnpg_pg_database_size_bytes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", pod=~\"$instances\"}",
     "legendFormat": "{{datname}} ({{pod}})"
    }
   ]
  },
  {
   "title": "First Recoverability Point",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "max({__name__=~\"cnpg_collector_first_recoverability_point|barman_cloud_cloudnative_pg_io_first_recoverability_point\",cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"})*1000"
    }
   ]
  },
  { "title": "Server Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  { "title": "Instance", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 0, "y": 8 } },
  { "title": "Status", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 3, "y": 8 } },
  { "title": "Clustering / replicas", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 5, "y": 8 } },
  { "title": "Zone", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 8, "y": 8 } },
  { "title": "Connections", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 10, "y": 8 } },
  { "title": "Max Connections", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 14, "y": 8 } },
  { "title": "Wraparound", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 17, "y": 8 } },
  { "title": "Started", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 20, "y": 8 } },
  { "title": "Version", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 22, "y": 8 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "repeat": "instances",
   "options": {
    "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n  <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><p style=\"font-weight: bold;\">$instances</p>\n  </td>\n</table>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 9 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "min(kube_pod_container_status_ready{cluster=~\"$k8s_cluster\",container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 9 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "1 - cnpg_pg_replication_in_recovery{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"} + cnpg_pg_replication_is_wal_receiver_up{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 7, "y": 9 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "cnpg_pg_replication_streaming_replicas{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\", pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "This metric depends on exporting the: `topology.kubernetes.io/zone` label through kube-state-metrics (not enabled by default). Can be added by changing its configuration with:\n\n```yaml\nmetricLabelsAllowlist:\n  - nodes=[topology.kubernetes.io/zone]\n```",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "kube_pod_info{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\", pod=~\"$instances\"} * on(node,instance) group_left(label_topology_kubernetes_io_zone) kube_node_labels{cluster=~\"$k8s_cluster\"}",
     "legendFormat": "{{pod}} -> {{label_topology_kubernetes_io_zone}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 9 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "sum by (pod) (cnpg_backends_total{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\", pod=~\"$instances\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 9 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "100 * sum by (pod) (cnpg_backends_total{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\", pod=~\"$instances\"}) / sum by (pod) (cnpg_pg_settings_setting{cluster=~\"$k8s_cluster\",name=\"max_connections\", namespace=~\"$namespace\", pod=~\"$instances\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 9 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "max by (pod) (cnpg_pg_database_xid_age{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\", pod=~\"$instances\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 9 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "cnpg_pg_postmaster_start_time{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\", pod=~\"$instances\"}*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "cnpg_collector_postgres_version{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\", pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    { "title": "Instance", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 0, "y": 295 } },
    { "title": "Max Connections", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 3, "y": 295 } },
    { "title": "Shared Buffers", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 6, "y": 295 } },
    { "title": "Effective Cache Size", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 9, "y": 295 } },
    { "title": "Work Mem", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 12, "y": 295 } },
    { "title": "Maintenance Work Mem", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 15, "y": 295 } },
    { "title": "Random Page Cost", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 18, "y": 295 } },
    { "title": "Sequential Page Cost", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 21, "y": 295 } },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 296 },
     "repeat": "instances",
     "options": {
      "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n  <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><p style=\"font-weight: bold;\">$instances</p>\n  </td>\n</table>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 296 },
     "repeat": "instances",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "cnpg_pg_settings_setting{cluster=~\"$k8s_cluster\",name=\"max_connections\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 296 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "max by (pod) (cnpg_pg_settings_setting{cluster=~\"$k8s_cluster\",name=\"shared_buffers\",namespace=~\"$namespace\",pod=~\"$instances\"}) * max by (pod) (cnpg_pg_settings_setting{cluster=~\"$k8s_cluster\",name=\"block_size\",namespace=~\"$namespace\",pod=~\"$instances\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 296 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "max by (pod) (cnpg_pg_settings_setting{cluster=~\"$k8s_cluster\",name=\"effective_cache_size\",namespace=~\"$namespace\",pod=~\"$instances\"}) * max by (pod) (cnpg_pg_settings_setting{cluster=~\"$k8s_cluster\",name=\"block_size\",namespace=~\"$namespace\",pod=~\"$instances\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 296 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "cnpg_pg_settings_setting{cluster=~\"$k8s_cluster\",name=\"work_mem\",namespace=~\"$namespace\",pod=~\"$instances\"} * 1024",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 296 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "cnpg_pg_settings_setting{cluster=~\"$k8s_cluster\",name=\"maintenance_work_mem\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 296 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "cnpg_pg_settings_setting{cluster=~\"$k8s_cluster\",name=\"random_page_cost\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 296 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "cnpg_pg_settings_setting{cluster=~\"$k8s_cluster\",name=\"seq_page_cost\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Configurations",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 302 },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "cnpg_pg_settings_setting{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}: {{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Operational Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$k8s_cluster\",pod=~\"$instances\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (container memory working set)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"$k8s_cluster\",pod=~\"$instances\", namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Session States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "sum(cnpg_backends_total{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}) by (pod)",
     "legendFormat": "Total ({{pod}})"
    },
    {
     "app": "grafana-assistant-app",
     "expr": "sum(cnpg_backends_total{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}) by (state, pod)",
     "legendFormat": "{{state}} ({{pod}})"
    }
   ]
  },
  {
   "title": "Transactions [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "sum(rate(cnpg_pg_stat_database_xact_commit{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m])) by (pod)",
     "legendFormat": "Commit ({{pod}})"
    },
    {
     "app": "grafana-assistant-app",
     "expr": "sum(rate(cnpg_pg_stat_database_xact_rollback{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m])) by (pod)",
     "legendFormat": "Rollback ({{pod}})"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "max by (pod) (cnpg_backends_max_tx_duration_seconds{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Deadlocks [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "rate(cnpg_pg_stat_database_deadlocks{cluster=~\"$k8s_cluster\",datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Blocked Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "cnpg_backends_waiting_total{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Storage & I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume Space Usage: PGDATA and WAL",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 322 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"})",
       "legendFormat": "PGDATA ({{persistentvolumeclaim}})"
      },
      {
       "app": "grafana-assistant-app",
       "expr": "max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"})",
       "legendFormat": "WAL ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Volume Inode Usage: PGDATA and WAL",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 322 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "max by(persistentvolumeclaim) (kubelet_volume_stats_inodes_used{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"} / kubelet_volume_stats_inodes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"})",
       "legendFormat": "PGDATA ({{persistentvolumeclaim}})"
      },
      {
       "app": "grafana-assistant-app",
       "expr": "max by(persistentvolumeclaim) (kubelet_volume_stats_inodes_used{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"} / kubelet_volume_stats_inodes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"})",
       "legendFormat": "WAL ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Volume Space Usage: Tablespaces",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 330 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "sum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-tbs.*\"}) \n/\nsum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=~\"$k8s_cluster\",namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-tbs.*\"}) \n*\non(namespace, persistentvolumeclaim) group_left(volume,pod)\nkube_pod_spec_volumes_persistentvolumeclaims_info{cluster=~\"$k8s_cluster\",pod=~\"$instances\"}",
       "legendFormat": "{{volume}} ({{pod}})"
      }
     ]
    },
    {
     "title": "Tuple I/O [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 337 },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "sum(rate(cnpg_pg_stat_database_tup_deleted{cluster=~\"$k8s_cluster\",datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m]))",
       "legendFormat": "Deleted"
      },
      {
       "app": "grafana-assistant-app",
       "expr": "sum(rate(cnpg_pg_stat_database_tup_inserted{cluster=~\"$k8s_cluster\",datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m]))",
       "legendFormat": "Inserted"
      },
      {
       "app": "grafana-assistant-app",
       "expr": "sum(rate(cnpg_pg_stat_database_tup_fetched{cluster=~\"$k8s_cluster\",datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m]))",
       "legendFormat": "Fetched"
      },
      {
       "app": "grafana-assistant-app",
       "expr": "sum(rate(cnpg_pg_stat_database_tup_returned{cluster=~\"$k8s_cluster\",datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m]))",
       "legendFormat": "Returned"
      },
      {
       "app": "grafana-assistant-app",
       "expr": "sum(rate(cnpg_pg_stat_database_tup_updated{cluster=~\"$k8s_cluster\",datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m]))",
       "legendFormat": "Updated"
      }
     ]
    },
    {
     "title": "Block I/O [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 337 },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "rate(cnpg_pg_stat_database_blks_hit{cluster=~\"$k8s_cluster\",datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
       "legendFormat": "Blocks Hit ({{pod}})"
      },
      {
       "app": "grafana-assistant-app",
       "expr": "rate(cnpg_pg_stat_database_blks_read{cluster=~\"$k8s_cluster\",datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
       "legendFormat": "Blocks Read ({{pod}})"
      }
     ]
    },
    {
     "title": "Database Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 345 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "max by (datname) (cnpg_pg_database_size_bytes{cluster=~\"$k8s_cluster\",datname!~\"template.*\",datname!=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"})",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Temp Bytes [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 345 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "rate(cnpg_pg_stat_database_temp_bytes{cluster=~\"$k8s_cluster\",datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Ahead Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "WAL Segment Archive Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 323 },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "cnpg_collector_pg_wal_archive_status{cluster=~\"$k8s_cluster\",value=\"ready\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "ready ({{pod}})"
      },
      {
       "app": "grafana-assistant-app",
       "expr": "cnpg_collector_pg_wal_archive_status{cluster=~\"$k8s_cluster\",value=\"done\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "done ({{pod}})"
      }
     ]
    },
    {
     "title": "Archiver Status [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 323 },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "rate(cnpg_pg_stat_archiver_archived_count{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
       "legendFormat": "Archived ({{pod}})"
      },
      {
       "app": "grafana-assistant-app",
       "expr": "rate(cnpg_pg_stat_archiver_failed_count{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
       "legendFormat": "Failed ({{pod}})"
      }
     ]
    },
    {
     "title": "Last Archive Age",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 323 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "cnpg_pg_stat_archiver_seconds_since_last_archival{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "WAL Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 331 },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "cnpg_collector_pg_wal{cluster=~\"$k8s_cluster\",pod=~\"$instances\", namespace=~\"$namespace\", value=\"count\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 329 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "cnpg_pg_replication_lag{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Write Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 329 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "cnpg_pg_stat_replication_write_lag_seconds{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}} -> {{application_name}}"
      }
     ]
    },
    {
     "title": "Flush Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 329 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "cnpg_pg_stat_replication_flush_lag_seconds{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}} -> {{application_name}}"
      }
     ]
    },
    {
     "title": "Replay Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 329 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "cnpg_pg_stat_replication_replay_lag_seconds{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}} -> {{application_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Collector Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collection Duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 325 },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "cnpg_collector_collection_duration_seconds{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 325 },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "cnpg_collector_last_collection_error{cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "First Recoverability Point",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 326 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "{__name__=~\"cnpg_collector_first_recoverability_point|barman_cloud_cloudnative_pg_io_first_recoverability_point\",cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}*1000 > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requested/Timed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 327 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "{__name__=~\"cnpg_pg_stat_(bgwriter|checkpointer)_checkpoints_req\",cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "Requested ({{pod}})"
      },
      {
       "app": "grafana-assistant-app",
       "expr": "{__name__=~\"cnpg_pg_stat_(bgwriter|checkpointer)_checkpoints_timed\",cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "Timed ({{pod}})"
      }
     ]
    },
    {
     "title": "Write/Sync time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 327 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "{__name__=~\"cnpg_pg_stat_(bgwriter_checkpoint|checkpointer)_write_time\",cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "Write Time ({{pod}})"
      },
      {
       "app": "grafana-assistant-app",
       "expr": "{__name__=~\"cnpg_pg_stat_(bgwriter_checkpoint|checkpointer)_sync_time\",cluster=~\"$k8s_cluster\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "Sync Time ({{pod}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Extensions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Installed extensions",
     "type": "table",
     "description": "Show the installed extensions and their versions",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 351 },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "max(cnpg_pg_extensions_update_available{cluster=~\"$k8s_cluster\",pod=~\"$instances\", namespace=~\"$namespace\"}) by (datname, extname, default_version, installed_version)",
       "legendFormat": "{{datname}}: {{extname}} - {{installed_version}}/{{default_version}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 334 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "sum(kube_pod_status_ready{cluster=~\"$k8s_cluster\",namespace=\"$operatorNamespace\", pod=~\"cloudnative-pg.+|cnpg-controller-manager.+\", condition=\"true\"})"
      }
     ]
    },
    {
     "type": "stat",
     "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 334 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "max(controller_runtime_reconcile_total{cluster=~\"$k8s_cluster\",namespace=~\"$operatorNamespace\", result=\"error\", controller=\"cluster\"})"
      }
     ]
    },
    {
     "type": "stat",
     "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 334 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "max(controller_runtime_reconcile_total{cluster=~\"$k8s_cluster\",namespace=~\"$operatorNamespace\", result=\"error\", controller=\"backup\"})"
      }
     ]
    },
    {
     "type": "stat",
     "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 334 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "max(controller_runtime_reconcile_total{cluster=~\"$k8s_cluster\",namespace=~\"$operatorNamespace\", result=\"error\", controller=~\"scheduledbackup|scheduled-backup\"})"
      }
     ]
    },
    {
     "type": "stat",
     "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 334 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "max(controller_runtime_reconcile_total{cluster=~\"$k8s_cluster\",namespace=~\"$operatorNamespace\", result=\"error\", controller=\"pooler\"})"
      }
     ]
    },
    {
     "title": "Ready Operator Pods",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 336 },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "sum(kube_pod_status_ready{cluster=~\"$k8s_cluster\",namespace=\"$operatorNamespace\", pod=~\"cloudnative-pg.+|cnpg-controller-manager.+\", condition=\"true\"})"
      }
     ]
    },
    {
     "title": "Cluster Reconcile Errors",
     "type": "timeseries",
     "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 336 },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "max(controller_runtime_reconcile_total{cluster=~\"$k8s_cluster\",namespace=~\"$operatorNamespace\", result=\"error\", controller=\"cluster\"})"
      }
     ]
    },
    {
     "title": "Backup Reconcile Errors",
     "type": "timeseries",
     "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 336 },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "max(controller_runtime_reconcile_total{cluster=~\"$k8s_cluster\",namespace=~\"$operatorNamespace\", result=\"error\", controller=\"backup\"})"
      }
     ]
    },
    {
     "title": "Scheduled Backup Reconcile Errors",
     "type": "timeseries",
     "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 336 },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "max(controller_runtime_reconcile_total{cluster=~\"$k8s_cluster\",namespace=~\"$operatorNamespace\", result=\"error\", controller=~\"scheduledbackup|scheduled-backup\"})"
      }
     ]
    },
    {
     "title": "Pooler Reconcile Errors",
     "type": "timeseries",
     "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 336 },
     "targets": [
      {
       "app": "grafana-assistant-app",
       "expr": "max(controller_runtime_reconcile_total{cluster=~\"$k8s_cluster\",namespace=~\"$operatorNamespace\", result=\"error\", controller=\"pooler\"})"
      }
     ]
    }
   ]
  }
 ]
}